### ISSUE TITLE
tnf_value_domain.valid_from and valid_to

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenTNF/opentnf#9]
```
fields missing from the specification
```

Original issue reported on code.google.com by `larsn7113@gmail.com` on 7 Nov 2011 at 11:52

**Comment by larswik** [comment]
No action at the moment. Confusing with dates for both value domain and property

**Comment by larswik** [comment]
No action at the moment. Confusing with dates for both value domain and property. May be revoked if a need arises
